<?php

require_once dirname(__FILE__) . '/controller/TicketCommentEntityMetaController.php';
require_once dirname(__FILE__) . '/controller/TicketComment.php';
require_once dirname(__FILE__) . '/controller/TicketCommentUIController.php';
require_once dirname(__FILE__) . '/ticket_comments.admin.inc';

/**
 * Implements hook_entity_info().
 */
function ticket_comments_entity_info() {
  
  $info['ticket_comments'] = array(
    'label' => 'Ticket comment',
    'module' => 'tickets',
    'base table' => 'ticket_comments',
    'fieldable' => TRUE,
    'uri callback' => 'entity_class_uri',
    'access callback' => 'ticket_comments_access_callback',
    'label callback' => 'ticket_comments_label_callback',
    'controller class' => 'EntityAPIController', // 'Lgentity_Entity_MachineController',
    'entity class' => 'TicketCommentEntity',
    'metadata controller class' => 'EntityDefaultMetadataController',
    'entity keys' => array('id' => 'ticket_cid', 'bundle' => 'type'),
    'bundle keys' => array('bundle' => 'type'),
    'bundles' => array(
      'ticket_comments' => array(
        'label' => 'Ticket Comments',
        'admin' => array(
          'path' => 'admin/structure/ticket-comments',
          'access arguments' => array('administer ticket comments'),
        ),
      ),
    ),
    'admin ui' => array(
      'path' => 'admin/structure/ticket-comments',
      'file' => 'includes/tickets_category.admin.inc',
      'controller class' => 'EntityDefaultUIController',
    ),
  );
  
  return $info;
}



/**
 * Access callback for machine entity.
 */
function ticket_comments_access_callback($op, $entity, $account, $entity_type) {
  return user_access('administer ticket comment');
}

/**
 * Label callback for machine entity.
 */
function ticket_comments_label_callback($entity, $entity_type) {
  return ucwords($entity->name);
}
/**
 * Implements hook_ticket_view()
 */
function ticket_comments_ticket_view($ticket, $view_mode, $langcode) {
  if ($view_mode == 'full') {
      $ticket->content['comments'] = ticket_comments_page_additions($ticket);
  }
}

function ticket_comments_theme() {
  return array(
    'ticket_comments_wrapper' => array(
      'template' => 'ticket-comments-wrapper',
      'render element' => 'content',
    ),
  );
}

/**
 * Build the comment-related elements for ticket detail pages.
 *
 * @param $ticket
 *  A ticket object.
 */
function ticket_comments_page_additions($ticket) {
  module_load_include('inc', 'ticket_comments', 'ticket_comments');
  $ticket_comment = ticket_comments_create(array('type' => 'ticket_comments'));
//  kpr($ticket_comments);exit;
  $build = drupal_get_form('ticket_comments_form', $ticket_comment, 'add', 'ticket_comments', $ticket);
  $additions['comment_form'] = $build;
  
//  $ticket_comments = ticket_comments_load_multiple(array(), array('ticket_id' => 1));
  $ticket_comments = entity_load('ticket_comments' , FALSE , array('ticket_id' => 1), FALSE);
  kpr($ticket_comments);
  kpr($ticket->ticket_id);exit;
  $additions['comments_ticket'] = $ticket_comments;
  
  
  
  if ($additions) {
    $additions += array(
      '#theme' => 'ticket_comments_wrapper',
      '#ticket' => $ticket,
      'comments' => array(),
      'comment_form' => array(),
    );
  }
  return $additions;
}

//function ticket_comments_form($form, &$form_state, $ticket_comments) {
//  field_attach_form('ticket_comments', $ticket_comments, $form, $form_state);
//  return $form;
//}

