<?php

/**
 * @file
 * Module for the Ticket Entity - a starting point to create your own Entity
 * and associated administration interface
 */  


/**
 * Implement hook_entity_info().
 *
 * We define two entities here - the actual entity that will hold our domain
 * specific information and an entity that holds information about the different
 * types of entities. See here: http://drupal.org/node/977380 for a discussion on this
 * choice.
 */
function ticket_entity_info() {
  $return['ticket'] = array(
    'label' => t('Ticket'),
    // The entity class and controller class extend the classes provided by the
    // Entity API
    'entity class' => 'Ticket',
    'controller class' => 'TicketController',
    'base table' => 'ticket',
    'fieldable' => TRUE,
    'entity keys' => array(
        'id' => 'ticket_id',
        'bundle' => 'type',
    ),
    // Bundles are defined by the ticket types below
    'bundles' => array(),
    // Bundle keys tell the FieldAPI how to extract information from the bundle objects
    'bundle keys' => array(
      'bundle' => 'type',
    ),
    'label callback' => 'entity_class_label',
    'uri callback' => 'entity_class_uri',
    'creation callback' => 'ticket_create',
    'access callback' => 'ticket_access',
    'module' => 'ticket',
    // The information below is used by the TicketUIController (which extends the EntityDefaultUIController)
    'admin ui' => array(
      'path' => 'admin/content/tickets',
      'file' => 'ticket.admin.inc',
      'controller class' => 'TicketUIController',
      'menu wildcard' => '%ticket',
    ),
  );
  // The entity that holds information about the entity types	  
  $return['ticket_type'] = array(
    'label' => t('Ticket Type'),
    'entity class' => 'TicketType',
    'controller class' => 'TicketTypeController',
    'base table' => 'ticket_type',
    'fieldable' => FALSE,
    'bundle of' => 'ticket',
    'exportable' => TRUE,
    'entity keys' => array(
      'id' => 'id',
      'name' => 'type',
      'label' => 'label',
    ),
    'access callback' => 'ticket_type_access',
    'module' => 'ticket',
    // Enable the entity API's admin UI.
    'admin ui' => array(
      'path' => 'admin/structure/ticket_types',
      'file' => 'ticket_type.admin.inc',
      'controller class' => 'TicketTypeUIController',
    ),
  );

  return $return;
}

/**
 * Implements hook_field_extra_fields().
 */
function ticket_field_extra_fields() {
  $extra = array();

  foreach (ticket_get_types() as $type => $info) {
    $extra['ticket'][$type] = array(
      'form' => array(
        'title' => array(
          'label' => $info->label,
          'description' => t('Ticket module element'),
          'weight' => -5,
        ),
      ),
    );
  }

  return $extra;
}


/**
 * Implements hook_entity_info_alter().
 *
 * We are adding the info about the ticket types via a hook to avoid a recursion
 * issue as loading the ticket types requires the entity info as well.
 *
 * @todo This needs to be improved
 */
function ticket_entity_info_alter(&$entity_info) {
  foreach (ticket_get_types() as $type => $info) {
    $entity_info['ticket']['bundles'][$type] = array(
      'label' => $info->label,
      'admin' => array(
        'path' => 'admin/structure/ticket_types/manage/%ticket_type',
        'real path' => 'admin/structure/ticket_types/manage/' . $type,
        'bundle argument' => 4,
        'access arguments' => array('administer ticket types'),
      ),
    );
  }
}
  

/**
 * Implements hook_permission().
 */
function ticket_permission() {
  // We set up permisssions to manage entity types, manage all entities and the
  // permissions for each individual entity
  $permissions = array(
    'administer ticket types' => array(
      'title' => t('Administer ticket types'),
      'description' => t('Create and delete fields for ticket types, and set their permissions.'),
    ),
    'administer tickets' => array(
      'title' => t('Administer tickets'),
      'description' => t('Edit and delete all tickets'),
    ),  
  );
  
  //Generate permissions per ticket 
  foreach (ticket_get_types() as $type) {
    $type_name = check_plain($type->type);
    $permissions += array(
      "edit any $type_name ticket" => array(
        'title' => t('%type_name: Edit any ticket', array('%type_name' => $type->label)),
      ),
      "view any $type_name ticket" => array(
        'title' => t('%type_name: View any ticket', array('%type_name' => $type->label)),
      ),
    );
  }
  return $permissions;  
}


/**
 * Determines whether the given user has access to a ticket.
 *
 * @param $op
 *   The operation being performed. One of 'view', 'update', 'create', 'delete'
 *   or just 'edit' (being the same as 'create' or 'update').
 * @param $ticket
 *   Optionally a ticket or a ticket type to check access for. If nothing is
 *   given, access for all tickets is determined.
 * @param $account
 *   The user to check for. Leave it to NULL to check for the global user.
 * @return boolean
 *   Whether access is allowed or not.
 */
function ticket_access($op, $ticket = NULL, $account = NULL) {
  if (user_access('administer tickets', $account)) {
    return TRUE;
  }
  if (isset($ticket) && $type_name = $ticket->type) {
    $op = ($op == 'view') ? 'view' : 'edit';
    if (user_access("$op any $type_name ticket", $account)) {
      return TRUE;
    }
  }
  return FALSE;
}


/**
 * Access callback for the entity API.
 */
function ticket_type_access($op, $type = NULL, $account = NULL) {
  return user_access('administer ticket types', $account);
}


/**
 * Gets an array of all ticket types, keyed by the type name.
 *
 * @param $type_name
 *   If set, the type with the given name is returned.
 * @return TicketType[]
 *   Depending whether $type isset, an array of ticket types or a single one.
 */
function ticket_get_types($type_name = NULL) {
  // entity_load will get the Entity controller for our ticket entity and call the load
  // function of that object - we are loading entities by name here.
  $types = entity_load_multiple_by_name('ticket_type', isset($type_name) ? array($type_name) : FALSE);
  return isset($type_name) ? reset($types) : $types;
}


/**
 * Menu argument loader; Load a ticket type by string.
 *
 * @param $type
 *   The machine-readable name of a ticket type to load.
 * @return
 *   A ticket type array or FALSE if $type does not exist.
 */
function ticket_type_load($type) {
  return ticket_get_types($type);
}


/**
 * Fetch a ticket object. Make sure that the wildcard you choose 
 * in the ticket entity definition fits the function name here.
 *
 * @param $ticket_id
 *   Integer specifying the ticket id.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   A fully-loaded $ticket object or FALSE if it cannot be loaded.
 *
 * @see ticket_load_multiple()
 */
function ticket_load($ticket_id, $reset = FALSE) {
  $tickets = ticket_load_multiple(array($ticket_id), array(), $reset);
  return reset($tickets);
}


/**
 * Load multiple tickets based on certain conditions.
 *
 * @param $ticket_ids
 *   An array of ticket IDs.
 * @param $conditions
 *   An array of conditions to match against the {ticket} table.
 * @param $reset
 *   A boolean indicating that the internal cache should be reset.
 * @return
 *   An array of ticket objects, indexed by ticket_id.
 *
 * @see entity_load()
 * @see ticket_load()
 */
function ticket_load_multiple($ticket_ids = array(), $conditions = array(), $reset = FALSE) {
  return entity_load('ticket', $ticket_ids, $conditions, $reset);
}


/**
 * Deletes a ticket.
 */
function ticket_delete(Ticket $ticket) {
  $ticket->delete();
}


/**
 * Delete multiple tickets.
 *
 * @param $ticket_ids
 *   An array of ticket IDs.
 */
function ticket_delete_multiple(array $ticket_ids) {
  entity_get_controller('ticket')->delete($ticket_ids);
}


/**
 * Create a ticket object.
 */
function ticket_create($values = array()) {
  return entity_get_controller('ticket')->create($values);
}


/**
 * Saves a ticket to the database.
 *
 * @param $ticket
 *   The ticket object.
 */
function ticket_save(Ticket $ticket) {
  return $ticket->save();
}


/**
 * Saves a ticket type to the db.
 */
function ticket_type_save(TicketType $type) {
  $type->save();
}


/**
 * Deletes a ticket type from the db.
 */
function ticket_type_delete(TicketType $type) {
  $type->delete();
}


/**
 * URI callback for tickets
 */
function ticket_uri(Ticket $ticket){
  return array(
    'path' => 'ticket/' . $ticket->ticket_id,
  );
}


/**
 * Menu title callback for showing individual entities
 */
function ticket_page_title(Ticket $ticket){
  return $ticket->title;
}


/**
 * Sets up content to show an individual ticket
 * @todo - get rid of drupal_set_title();
 */
function ticket_page_view($ticket, $view_mode = 'full') {    
  $controller = entity_get_controller('ticket');  
  $content = $controller->view(array($ticket->ticket_id => $ticket));
  drupal_set_title($ticket->title);
  return $content;
}


/**
 * Implements hook_views_api().
 */
function ticket_views_api() {
  return array(
    'api' => 3,
    'path' => drupal_get_path('module', 'ticket') . '/views',
  );
}


/**
 * Implement hook_theme().
 */
function ticket_theme() {
  return array(
    'ticket_add_list' => array(
      'variables' => array('content' => array()),
      'file' => 'ticket.admin.inc',
    ),
    'ticket' => array(
      'render element' => 'elements',
      'template' => 'ticket',
    ),
   'ticket_sample_data' => array(
      'variables' => array('ticket_sample_data', 'ticket' => NULL),
      'template' => 'ticket-sample-data',
    ),


  );
}  


/**
 * Implements hook_menu_local_tasks_alter().
 */
function ticket_menu_local_tasks_alter(&$data, $router_item, $root_path) {
  // Add action link 'admin/structure/tickets/add' on 'admin/structure/tickets'.
  if ($root_path == 'admin/content/tickets') {
    $item = menu_get_item('admin/content/tickets/add');
    if ($item['access']) {
      $data['actions']['output'][] = array(
        '#theme' => 'menu_local_action',
        '#link' => $item,
      );
    }
  }
}


/**
 * The class used for ticket entities
 */
class Ticket extends Entity {
  
  public function __construct($values = array()) {
    parent::__construct($values, 'ticket');
  }

  protected function defaultLabel() {
    return $this->name;
  }

  protected function defaultUri() {
    return array('path' => 'ticket/' . $this->ticket_id);
  }
  
  
}


/**
 * The class used for ticket type entities
 */
class TicketType extends Entity {
  
  public $type;
  public $label;
  
  public function __construct($values = array()) {
    parent::__construct($values, 'ticket_type');
  }
  
}


/**
 * The Controller for Ticket entities
 */
class TicketController extends EntityAPIController {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }


  /**
   * Create a ticket - we first set up the values that are specific
   * to our ticket schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the ticket.
   *
   * @return
   *   A ticket object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Ticket
    $values += array( 
      'ticket_id' => '',
      'is_new' => TRUE,
      'title' => '',
      'created' => '',
      'changed' => '',
      'data' => '',
    );
    
    $ticket = parent::create($values);
    return $ticket;
  }
  
  /**
   * Overriding the buldContent function to add entity specific fields
   */
  public function buildContent($entity, $view_mode = 'full', $langcode = NULL, $content = array()) {
    $content = parent::buildContent($entity, $view_mode, $langcode, $content);
    $content['ticket_sample_data'] =  array(
      '#markup' => theme('ticket_sample_data', array('ticket_sample_data' => check_plain($entity->data['sample_data']), 'ticket' => $entity)),
    );

    return $content;
  }
  
}


/**
 * The Controller for Ticket entities
 */
class TicketTypeController extends EntityAPIControllerExportable {
  public function __construct($entityType) {
    parent::__construct($entityType);
  }
  
   /**
   * Create a ticket type - we first set up the values that are specific
   * to our ticket type schema but then also go through the EntityAPIController
   * function.
   * 
   * @param $type
   *   The machine-readable type of the ticket.
   *
   * @return
   *   A ticket type object with all default fields initialized.
   */
  public function create(array $values = array()) {
    // Add values that are specific to our Ticket
    $values += array( 
      'id' => '',
      'is_new' => TRUE,
      'data' => '',
    );
    $ticket_type = parent::create($values);
    return $ticket_type;
  }

}